### ISSUE TITLE
No dev script in package.json

### ISSUE THREAD

**Issue by allrude** [vuefront/vuefront#10]
tried to install but nothing, guess the documentation is not up to date

**Comment by dmitriyzhuk** [comment]
Hi, if you want to try out vuefront, simply follow these steps:
1. Install CMS Connect APP. ex. [wordpress](https://github.com/vuefront/wordpress) 
2. Create VueFront App
```
# Create VueFront app. replace <project-name> with vuefront
yarn create vuefront-app <project-name>
# OR npx create-vuefront-app <project-name>

yarn dev
```

When Asked to provide the CMS Connect URL, visit the plugin you installed in step one to get the url. 

If you actually want to edit VueFront core package (this repository), you will need to clone it separately and do `yarn link` to use it for the project. Just on its own vuefront/vuefront is just a library. it won't build an app. it actually is a dependency for another repo - vuefront/vuefront-nuxt which is then fetching it and loads it in the NUXT app. 

If you need more details, contact me on discord https://discord.gg/C9vcTCQ
