### ISSUE TITLE
Going to the CMS Connect URL returns errors

### ISSUE THREAD

**Issue by willie89** [vuefront/vuefront#3]
\n\n1: \n ^\n","category":"graphql","locations":[{"line":1,"column":1}]}]}
{"errors":[{"message":"Syntax Error GraphQL (1:1) Unexpected

**Comment by nzxt** [comment]
It's normal behavior.
Same question answere [here](https://github.com/vuefront/vuefront/issues/1#issuecomment-504896902) by @dmitriyzhuk

**Comment by dmitriyzhuk** [comment]
it is normal behavior, yet it is very misleading. We will add a response page for a GET request to graphql in the next versions.
