### ISSUE TITLE
Nothing in components folder

### ISSUE THREAD

**Issue by ludo1960** [vuefront/vuefront#9]
Hi,
after following your installation instructions I'm left with an empty components folder and an empty store directory (well except a blank index.js file)

And when i run npm run dev I get "Network error: Response not successful: Received status code 405" when attempting to connect to  a working JSON API http://mysite.com/api

What gives?

Thanks...

**Comment by dmitriyzhuk** [comment]
Hi, 

For vuefront to work properly, you need to first:
1. Install a CMS Connect App on your CMS (like [wordpress](https://github.com/vuefront/wordpress))
2. Create VueFront App with 
```
# Create VueFront app. replace <project-name> with vuefront
yarn create vuefront-app <project-name>
# OR npx create-vuefront-app <project-name>

yarn dev
```
and when asked, provide the CMS Connect URL you were given when installing the CMS Connect App (step 1)

That is it. if you need more details, you can find me on discord at https://discord.gg/C9vcTCQ

**Comment by devmade** [comment]
+1 to @ludo1960 I am facing the same issue. There's literally nothing in components and all other directories. I tried to install twice. And yes I did run the npx create-vuefront-app command.
